### ISSUE TITLE
github-pages 설정 변경 후에도 Active 상태 유지

### ISSUE THREAD

**Issue by dev-wooyeon** [ieunune/protectedWeb#1]
github-pages 기능 테스트로 인덱스 파일 테스트 하고 원복 하였으나
Active 상태 유지되고 있어. 접근 가능하고 404에러 응답 중.
이력 삭제 방법이나, Active 상태 수동으로 처리할 수 있는 방법 필요.

**Comment by ieunune** [comment]
> 

Settings -> Environments -> github_pages 
비밀번호 입력 후 삭제 확인 버튼 클릭하여 해결 가능.

**Comment by dev-wooyeon** [comment]
> github-pages 기능 테스트로 인덱스 파일 테스트 하고 원복 하였으나 Active 상태 유지되고 있어. 접근 가능하고 404에러 응답 중. 이력 삭제 방법이나, Active 상태 수동으로 처리할 수 있는 방법 필요.

Settings -> Environments -> github_pages
비밀번호 입력 후 삭제 확인 버튼 클릭하여 해결 가능.
